name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13 ]
        build_type: [ Release ]
        c_compiler: [ gcc-13, clang-17, cl ]
        include:
          - os: windows-2022
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-22.04
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - os: ubuntu-22.04
            c_compiler: clang-17
            cpp_compiler: clang++-17
          - os: macos-13
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - os: macos-13
            c_compiler: clang-17
            cpp_compiler: clang++-17
        exclude:
          - os: windows-2022
            c_compiler: gcc-13
          - os: windows-2022
            c_compiler: clang-17
          - os: ubuntu-22.04
            c_compiler: cl
          - os: macos-13
            c_compiler: cl
    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install

      - name: Set up vcpkg (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install

      - name: Install dependencies
        run: |
          cd vcpkg
          ./vcpkg install

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}